-- MorningDesk Supabase prototype table
--
-- How to use:
-- 1. Create a Supabase project.
-- 2. Open SQL Editor.
-- 3. Run this script.
-- 4. In MorningDesk Settings > PC·휴대폰 동기화:
--    - 저장 방식: 온라인 동기화
--    - Supabase URL: Project URL
--    - Supabase anon key: Project API anon public key
--    - 프로필 키: use "안전한 프로필 키 만들기" and reuse the same key on each device.
--
-- Prototype privacy note:
-- This no-login prototype uses a long unguessable profile key as the row id
-- through two RPC functions. The table itself has no anon RLS policy, so anon
-- clients cannot enumerate rows through the REST table endpoint.
-- Do not store company secrets, passwords, API keys, or sensitive personal data.
-- For stronger privacy, add Supabase Auth later and replace these anon policies
-- with auth.uid()-based policies.

create table if not exists public.morningdesk_state (
  id text primary key,
  state jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.morningdesk_state enable row level security;

drop policy if exists "morningdesk prototype read" on public.morningdesk_state;
drop policy if exists "morningdesk prototype insert" on public.morningdesk_state;
drop policy if exists "morningdesk prototype update" on public.morningdesk_state;

create or replace function public.morningdesk_load(profile_key text)
returns table(state jsonb, updated_at timestamptz)
language sql
security definer
set search_path = public
as $$
  select saved.state, saved.updated_at
  from public.morningdesk_state as saved
  where length(profile_key) >= 20
    and saved.id = profile_key
  limit 1;
$$;

create or replace function public.morningdesk_save(profile_key text, next_state jsonb)
returns timestamptz
language plpgsql
security definer
set search_path = public
as $$
declare
  saved_at timestamptz;
begin
  if profile_key is null or length(profile_key) < 20 then
    raise exception 'profile key must be at least 20 characters';
  end if;

  insert into public.morningdesk_state (id, state, updated_at)
  values (profile_key, next_state, now())
  on conflict (id) do update
    set state = excluded.state,
        updated_at = excluded.updated_at
  returning morningdesk_state.updated_at into saved_at;

  return saved_at;
end;
$$;

revoke all on function public.morningdesk_load(text) from public;
revoke all on function public.morningdesk_save(text, jsonb) from public;
grant execute on function public.morningdesk_load(text) to anon;
grant execute on function public.morningdesk_save(text, jsonb) to anon;

create index if not exists morningdesk_state_updated_at_idx
on public.morningdesk_state (updated_at desc);

-- Web Push subscriptions are private server data. The browser never reads this
-- table directly; only the morningdesk-push Edge Function uses service_role.
create table if not exists public.morningdesk_push_subscriptions (
  id bigint generated by default as identity primary key,
  profile_id text not null,
  endpoint_hash text not null unique,
  subscription jsonb not null,
  device_label text not null default 'device',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.morningdesk_push_subscriptions enable row level security;

create index if not exists morningdesk_push_profile_idx
on public.morningdesk_push_subscriptions (profile_id, active);

-- One row claims one scheduled reminder before it is sent. This prevents a
-- minute-based Cron retry from sending the same reminder more than once.
create table if not exists public.morningdesk_push_delivery_log (
  id bigint generated by default as identity primary key,
  profile_id text not null,
  delivery_key text not null unique,
  schedule_day date not null,
  created_at timestamptz not null default now()
);

alter table public.morningdesk_push_delivery_log enable row level security;

create index if not exists morningdesk_push_delivery_day_idx
on public.morningdesk_push_delivery_log (schedule_day);
